version: "3.9"

services:
  backend:
    image: python:3.12-slim
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      PYTHONPATH: /app/src
    volumes:
      - ../backend:/app
    ports:
      - "8000:8000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "corepack enable && pnpm install --frozen-lockfile && pnpm dev --host 0.0.0.0 --port 5173"
    volumes:
      - ../frontend:/app
    ports:
      - "5173:5173"
    tty: true
